approve:
- commandHelpLink: ""
  repos:
  - openshift/crontab-plugin
  require_self_approval: false
lgtm:
- repos:
  - openshift/crontab-plugin
  review_acts_as_lgtm: true
plugins:
  openshift/crontab-plugin:
    plugins:
    - approve
